### ISSUE TITLE
Strange bug, wrong indicator being shown/unshown in modeline

### ISSUE THREAD

**Issue by linuxer0x42** [protesilaos/notmuch-indicator#1]
Hi Prot, great package, I was looking for this for a while!

I have a strange bug with notmuch-indicator where if you turn the mode on, instead of turning `notmuch-indicator-mode` on it turns on `display-time-mode` and turns it off.

Linked video:

https://user-images.githubusercontent.com/82241382/191722368-bf7d1c15-08b8-4466-ab12-1d349ec6a81a.mp4

**Comment by linuxer0x42** [comment]
It might be something wrong with my Emacs config? idk

**Comment by linuxer0x42** [comment]
For some reason it worked perfectly yesterday with the same config.

**Comment by linuxer0x42** [comment]
Cannot reproduce with `emacs -q`.

**Comment by protesilaos** [comment]
Hello @yusi1 and thanks for taking the time to report this!

I suspect it has something to do with how the `notmuch-indicator` is affecting the `global-mode-string` in your setup.

Can you restart your Emacs without the `notmuch-indicator-mode` and check the value of `global-mode-string`?  That will give us a better idea of what is going on.

**Comment by linuxer0x42** [comment]
> Hello @yusi1 and thanks for taking the time to report this!
> 
> I suspect it has something to do with how the `notmuch-indicator` is affecting the `global-mode-string` in your setup.
> 
> Can you restart your Emacs without the `notmuch-indicator-mode` and check the value of `global-mode-string`? That will give us a better idea of what is going on.

Okay, so I restarted Emacs without `notmuch-indicator-mode` activated and this is the value of `global-mode-string`:
`("" display-time-string battery-mode-line-string)`

**Comment by linuxer0x42** [comment]
Just now I set the variable `notmuch-indicator-hide-empty-counters` to `nil` and the counters show up, but for some reason they are all zero, even though when I open `notmuch` it does show my emails and unread/read ones.

**Comment by linuxer0x42** [comment]
I tried doing the commands that the indicator uses to get unread emails from the cli, and they work.

**Comment by protesilaos** [comment]
> Okay, so I restarted Emacs without `notmuch-indicator-mode` activated and this is the value of `global-mode-string`: `("" display-time-string battery-mode-line-string)`

Okay.  Now please activate `notmuch-indicator-mode` and check the value of `notmuch-indicator--last-state`.

I suspect the value of that variable is giving us a false positive and the current code is removing something it shouldn't.

**Comment by protesilaos** [comment]
> Just now I set the variable `notmuch-indicator-hide-empty-counters` to `nil` and the counters show up, but for some reason they are all zero.

Was the mode already enabled?  Perhaps the counters have not been refreshed yet per the `notmuch-indicator-refresh-count`?

**Comment by linuxer0x42** [comment]
> > Okay, so I restarted Emacs without `notmuch-indicator-mode` activated and this is the value of `global-mode-string`: `("" display-time-string battery-mode-line-string)`
> 
> Okay. Now please activate `notmuch-indicator-mode` and check the value of `notmuch-indicator--last-state`.
> 
> I suspect the value of that variable is giving us a false positive and the current code is removing something it shouldn't.

Nvm, sorry about this, it was a problem with my setup, the crontab that fetches mail didn't run so the indicator was correct.

I really should've done more debugging before I opened this issue, but thanks for helping!

**Comment by linuxer0x42** [comment]
BTW it works now that I fetched mail manually from the cli, the indicator shows the correct readings for unread messages.

**Comment by protesilaos** [comment]
Okay about the fetching/counting part.  But what about the `global-mode-string`?  I thought this was a separate issue or maybe not?

EDIT: add question mark.

**Comment by linuxer0x42** [comment]
> Okay about the fetching/counting part. But what about the `global-mode-string`. I thought this was a separate issue or maybe not?

No it wasn't a separate issue, because I had that variable to hide empty counters set to `t` and it was correct that there wasn't any unread emails for today, because no emails were fetched today because my crontab failed to run for some reason.

EDIT: It is a separate issue.

**Comment by protesilaos** [comment]
Alright then!

**Comment by linuxer0x42** [comment]
> Alright then!

Actually nevermind, yeah I think the wrong mode being turned on/off was a separate issue, but I don't know what caused it, sorry, I didn't understand what you meant at first lol.

**Comment by linuxer0x42** [comment]
Because if `notmuch-indicator-mode` is enabled and that variable to hide empty counters is set to `t`, and there aren't any unread emails for today, it shouldn't turn another mode on/off.

**Comment by protesilaos** [comment]
Okay.  Check again what I wrote here: https://github.com/protesilaos/notmuch-indicator/issues/1#issuecomment-1254871734

**Comment by linuxer0x42** [comment]
> Okay. Check again what I wrote here: [#1 (comment)](https://github.com/protesilaos/notmuch-indicator/issues/1#issuecomment-1254871734)

Alright, I restarted Emacs with it enabled and it shows this for the value of `notmuch-indicator--last-state`:
`"PE@1  ED@19  EB@26  "`

EDIT: I also set the variable `notmuch-indicator-hide-empty-counters` to `t` again, should I turn it off?

**Comment by protesilaos** [comment]
> EDIT: I also set the variable notmuch-indicator-hide-empty-counters to t again, should I turn it off?

No, let it be and we check how this goes.

> Alright, I restarted Emacs with it enabled and it shows this for the value of notmuch-indicator--last-state:
"PE@1 ED@19 EB@26 "

And the value of the `global-mode-string` is what now?

**Comment by linuxer0x42** [comment]
> > EDIT: I also set the variable notmuch-indicator-hide-empty-counters to t again, should I turn it off?
> 
> No, let it be and we check how this goes.

Okay, no problem.

> > Alright, I restarted Emacs with it enabled and it shows this for the value of notmuch-indicator--last-state:
> > "PE@1 ED@19 EB@26 "
> 
> And the value of the `global-mode-string` is what now?

It is:
`("PE@1  ED@19  EB@26  " "" display-time-string battery-mode-line-string)`

**Comment by protesilaos** [comment]
I am trying this, to emulate what the code is doing:

```elisp
(setq testing '("PE@1 ED@19 EB@26 " "" display-time-string battery-mode-line-string))

(let ((indicator "PE@1 ED@19 EB@26 " ))
  (setq testing (delete indicator testing)))
```

But the return value I get from the `let` form is as expected:

```elisp
("" display-time-string battery-mode-line-string)
```

We are missing something, but I am not yet sure what that is.

**Comment by protesilaos** [comment]
I notice that the `global-mode-string` uses symbols for the other items, whereas we add a string directly.  Let me try to add a variable that holds the string instead.

**Comment by linuxer0x42** [comment]
> I notice that the `global-mode-string` uses symbols for the other items, whereas we add a string directly. Let me try to add a variable that holds the string instead.

Okay

**Comment by linuxer0x42** [comment]
So I think before when I had 0 for all the counters the last state was `" "`, so I tried this and it deletes it properly.

```
(setq testing '(" " "" display-time-string battery-mode-line-string))

(let ((indicator " " ))
  (setq testing (delete indicator testing)))
```

Edit: When I had that variable to hide empty counters set to `t`.

**Comment by protesilaos** [comment]
I think I have fixed the issue for good.  Can you try this diff or do you prefer for me to format it as a patch?

```diff
 notmuch-indicator.el | 32 +++++++++++++++++++-------------
 1 file changed, 19 insertions(+), 13 deletions(-)

diff --git a/notmuch-indicator.el b/notmuch-indicator.el
index 3c52151..87529c2 100644
--- a/notmuch-indicator.el
+++ b/notmuch-indicator.el
@@ -190,21 +190,27 @@ (defun notmuch-indicator--return-count ()
      (notmuch-indicator--format-output props))
    notmuch-indicator-args))
 
-(defvar notmuch-indicator--last-state nil
-  "Internal variable used to store the indicator's state.")
+(defvar notmuch-indicator-string ""
+  "String showing the `notmuch-indicator' state.
+It is appended to the `global-mode-string'.")
+(put 'notmuch-indicator-string 'risky-local-variable t)
 
 (defun notmuch-indicator--indicator ()
   "Prepare new mail count mode line indicator."
-  (let* ((count (notmuch-indicator--return-count))
-         (old-indicator notmuch-indicator--last-state))
-    (when old-indicator
-      (setq global-mode-string (delete old-indicator global-mode-string)))
-    (cond
-     (count
-      (setq global-mode-string (push count global-mode-string))
-      (setq notmuch-indicator--last-state count))
-     (t
-      (setq notmuch-indicator--last-state nil))))
+  (when (not (string-empty-p notmuch-indicator-string))
+    (setq global-mode-string (delq 'notmuch-indicator-string global-mode-string)))
+  (if-let ((count (notmuch-indicator--return-count)))
+      (setq notmuch-indicator-string count
+            ;; FIXME 2022-09-22: This may be hacky, but I cannot remember or
+            ;; find a function that appends an element as the second in a
+            ;; list.  I don't want it to be at the very start or end...
+            global-mode-string
+            (reverse
+             (append
+              (butlast (reverse global-mode-string))
+              '(notmuch-indicator-string)
+              '(""))))
+    (setq notmuch-indicator-string ""))
   (force-mode-line-update t))
 
 (defun notmuch-indicator--running-p ()
@@ -244,7 +250,7 @@ (define-minor-mode notmuch-indicator-mode
         (dolist (fn notmuch-indicator-force-refresh-commands)
           (advice-add fn :after #'notmuch-indicator--refresh)))
     (cancel-function-timers #'notmuch-indicator--indicator)
-    (setq global-mode-string (delete notmuch-indicator--last-state global-mode-string))
+    (setq global-mode-string (delq 'notmuch-indicator-string global-mode-string))
     (dolist (fn notmuch-indicator-force-refresh-commands)
       (advice-remove fn #'notmuch-indicator--refresh))
     (force-mode-line-update t)))

```

EDIT: stylistic tweaks to the code.

**Comment by linuxer0x42** [comment]
> I think I have fixed the issue for good. Can you try this diff or do you prefer for me to format it as a patch?
> 
> ```diff
>  notmuch-indicator.el | 32 +++++++++++++++++++-------------
>  1 file changed, 19 insertions(+), 13 deletions(-)
> 
> diff --git a/notmuch-indicator.el b/notmuch-indicator.el
> index 3c52151..87529c2 100644
> --- a/notmuch-indicator.el
> +++ b/notmuch-indicator.el
> @@ -190,21 +190,27 @@ (defun notmuch-indicator--return-count ()
>       (notmuch-indicator--format-output props))
>     notmuch-indicator-args))
>  
> -(defvar notmuch-indicator--last-state nil
> -  "Internal variable used to store the indicator's state.")
> +(defvar notmuch-indicator-string ""
> +  "String showing the `notmuch-indicator' state.
> +It is appended to the `global-mode-string'.")
> +(put 'notmuch-indicator-string 'risky-local-variable t)
>  
>  (defun notmuch-indicator--indicator ()
>    "Prepare new mail count mode line indicator."
> -  (let* ((count (notmuch-indicator--return-count))
> -         (old-indicator notmuch-indicator--last-state))
> -    (when old-indicator
> -      (setq global-mode-string (delete old-indicator global-mode-string)))
> -    (cond
> -     (count
> -      (setq global-mode-string (push count global-mode-string))
> -      (setq notmuch-indicator--last-state count))
> -     (t
> -      (setq notmuch-indicator--last-state nil))))
> +  (when (not (string-empty-p notmuch-indicator-string))
> +    (setq global-mode-string (delq 'notmuch-indicator-string global-mode-string)))
> +  (if-let ((count (notmuch-indicator--return-count)))
> +      (setq notmuch-indicator-string count
> +            ;; FIXME 2022-09-22: This may be hacky, but I cannot remember or
> +            ;; find a function that appends an element as the second in a
> +            ;; list.  I don't want it to be at the very start or end...
> +            global-mode-string
> +            (reverse
> +             (append
> +              (butlast (reverse global-mode-string))
> +              '(notmuch-indicator-string)
> +              '(""))))
> +    (setq notmuch-indicator-string ""))
>    (force-mode-line-update t))
>  
>  (defun notmuch-indicator--running-p ()
> @@ -244,7 +250,7 @@ (define-minor-mode notmuch-indicator-mode
>          (dolist (fn notmuch-indicator-force-refresh-commands)
>            (advice-add fn :after #'notmuch-indicator--refresh)))
>      (cancel-function-timers #'notmuch-indicator--indicator)
> -    (setq global-mode-string (delete notmuch-indicator--last-state global-mode-string))
> +    (setq global-mode-string (delq 'notmuch-indicator-string global-mode-string))
>      (dolist (fn notmuch-indicator-force-refresh-commands)
>        (advice-remove fn #'notmuch-indicator--refresh))
>      (force-mode-line-update t)))
> ```
> 
> EDIT: stylistic tweaks to the code.

I would prefer a patch tbh.

**Comment by protesilaos** [comment]
I cannot attach a patch file here.  Github rejects.  Save those contents to a `.patch` file and give it a try:

```patch
From c25a06f31343abb2bd45687ec51e5dc3257e0fb7 Mon Sep 17 00:00:00 2001
Message-Id: <c25a06f31343abb2bd45687ec51e5dc3257e0fb7.1663859681.git.info@protesilaos.com>
From: Protesilaos Stavrou <info@protesilaos.com>
Date: Thu, 22 Sep 2022 18:11:50 +0300
Subject: [PATCH] Fix how indicator is added to global-mode-string

We want to pass it as a symbol instead of a string.  This is how other
modes do it as well.  The result is still the same for the user, though
this design ensures that we do not get false positives when we try to
remove our indicator (e.g. if we target an empty string, we can delete
something else).

Thanks to Yusef Aslam for reporting a bug which revealed this problem.
This was done in issue 1 over at the GitHub mirror:
<https://github.com/protesilaos/notmuch-indicator/issues/1>.
---
 notmuch-indicator.el | 32 +++++++++++++++++++-------------
 1 file changed, 19 insertions(+), 13 deletions(-)

diff --git a/notmuch-indicator.el b/notmuch-indicator.el
index 3c52151..87529c2 100644
--- a/notmuch-indicator.el
+++ b/notmuch-indicator.el
@@ -190,21 +190,27 @@ (defun notmuch-indicator--return-count ()
      (notmuch-indicator--format-output props))
    notmuch-indicator-args))
 
-(defvar notmuch-indicator--last-state nil
-  "Internal variable used to store the indicator's state.")
+(defvar notmuch-indicator-string ""
+  "String showing the `notmuch-indicator' state.
+It is appended to the `global-mode-string'.")
+(put 'notmuch-indicator-string 'risky-local-variable t)
 
 (defun notmuch-indicator--indicator ()
   "Prepare new mail count mode line indicator."
-  (let* ((count (notmuch-indicator--return-count))
-         (old-indicator notmuch-indicator--last-state))
-    (when old-indicator
-      (setq global-mode-string (delete old-indicator global-mode-string)))
-    (cond
-     (count
-      (setq global-mode-string (push count global-mode-string))
-      (setq notmuch-indicator--last-state count))
-     (t
-      (setq notmuch-indicator--last-state nil))))
+  (when (not (string-empty-p notmuch-indicator-string))
+    (setq global-mode-string (delq 'notmuch-indicator-string global-mode-string)))
+  (if-let ((count (notmuch-indicator--return-count)))
+      (setq notmuch-indicator-string count
+            ;; FIXME 2022-09-22: This may be hacky, but I cannot remember or
+            ;; find a function that appends an element as the second in a
+            ;; list.  I don't want it to be at the very start or end...
+            global-mode-string
+            (reverse
+             (append
+              (butlast (reverse global-mode-string))
+              '(notmuch-indicator-string)
+              '(""))))
+    (setq notmuch-indicator-string ""))
   (force-mode-line-update t))
 
 (defun notmuch-indicator--running-p ()
@@ -244,7 +250,7 @@ (define-minor-mode notmuch-indicator-mode
         (dolist (fn notmuch-indicator-force-refresh-commands)
           (advice-add fn :after #'notmuch-indicator--refresh)))
     (cancel-function-timers #'notmuch-indicator--indicator)
-    (setq global-mode-string (delete notmuch-indicator--last-state global-mode-string))
+    (setq global-mode-string (delq 'notmuch-indicator-string global-mode-string))
     (dolist (fn notmuch-indicator-force-refresh-commands)
       (advice-remove fn #'notmuch-indicator--refresh))
     (force-mode-line-update t)))
-- 
2.37.3
```

**Comment by linuxer0x42** [comment]
> I cannot attach a patch file here. Github rejects. Save those contents to a `.patch` file and give it a try:
> 
> ```diff
> From c25a06f31343abb2bd45687ec51e5dc3257e0fb7 Mon Sep 17 00:00:00 2001
> Message-Id: <c25a06f31343abb2bd45687ec51e5dc3257e0fb7.1663859681.git.info@protesilaos.com>
> From: Protesilaos Stavrou <info@protesilaos.com>
> Date: Thu, 22 Sep 2022 18:11:50 +0300
> Subject: [PATCH] Fix how indicator is added to global-mode-string
> 
> We want to pass it as a symbol instead of a string.  This is how other
> modes do it as well.  The result is still the same for the user, though
> this design ensures that we do not get false positives when we try to
> remove our indicator (e.g. if we target an empty string, we can delete
> something else).
> 
> Thanks to Yusef Aslam for reporting a bug which revealed this problem.
> This was done in issue 1 over at the GitHub mirror:
> <https://github.com/protesilaos/notmuch-indicator/issues/1>.
> ---
>  notmuch-indicator.el | 32 +++++++++++++++++++-------------
>  1 file changed, 19 insertions(+), 13 deletions(-)
> 
> diff --git a/notmuch-indicator.el b/notmuch-indicator.el
> index 3c52151..87529c2 100644
> --- a/notmuch-indicator.el
> +++ b/notmuch-indicator.el
> @@ -190,21 +190,27 @@ (defun notmuch-indicator--return-count ()
>       (notmuch-indicator--format-output props))
>     notmuch-indicator-args))
>  
> -(defvar notmuch-indicator--last-state nil
> -  "Internal variable used to store the indicator's state.")
> +(defvar notmuch-indicator-string ""
> +  "String showing the `notmuch-indicator' state.
> +It is appended to the `global-mode-string'.")
> +(put 'notmuch-indicator-string 'risky-local-variable t)
>  
>  (defun notmuch-indicator--indicator ()
>    "Prepare new mail count mode line indicator."
> -  (let* ((count (notmuch-indicator--return-count))
> -         (old-indicator notmuch-indicator--last-state))
> -    (when old-indicator
> -      (setq global-mode-string (delete old-indicator global-mode-string)))
> -    (cond
> -     (count
> -      (setq global-mode-string (push count global-mode-string))
> -      (setq notmuch-indicator--last-state count))
> -     (t
> -      (setq notmuch-indicator--last-state nil))))
> +  (when (not (string-empty-p notmuch-indicator-string))
> +    (setq global-mode-string (delq 'notmuch-indicator-string global-mode-string)))
> +  (if-let ((count (notmuch-indicator--return-count)))
> +      (setq notmuch-indicator-string count
> +            ;; FIXME 2022-09-22: This may be hacky, but I cannot remember or
> +            ;; find a function that appends an element as the second in a
> +            ;; list.  I don't want it to be at the very start or end...
> +            global-mode-string
> +            (reverse
> +             (append
> +              (butlast (reverse global-mode-string))
> +              '(notmuch-indicator-string)
> +              '(""))))
> +    (setq notmuch-indicator-string ""))
>    (force-mode-line-update t))
>  
>  (defun notmuch-indicator--running-p ()
> @@ -244,7 +250,7 @@ (define-minor-mode notmuch-indicator-mode
>          (dolist (fn notmuch-indicator-force-refresh-commands)
>            (advice-add fn :after #'notmuch-indicator--refresh)))
>      (cancel-function-timers #'notmuch-indicator--indicator)
> -    (setq global-mode-string (delete notmuch-indicator--last-state global-mode-string))
> +    (setq global-mode-string (delq 'notmuch-indicator-string global-mode-string))
>      (dolist (fn notmuch-indicator-force-refresh-commands)
>        (advice-remove fn #'notmuch-indicator--refresh))
>      (force-mode-line-update t)))
> -- 
> 2.37.3
> ```

Thanks! I'll try it out later.

**Comment by yusi1** [comment]
Nice! So I archived all the emails sent today to test your patch when the indicator is at all zeroes, it doesn't delete the wrong minor mode from the modeline anymore, it does nothing, which is normal behavior (with the variable to hide empty counters set to `t`) compared to before.

**Comment by linuxer0x42** [comment]
Tested your patch when all the counters are zero (with the variable to hide empty counters set to `t`), and it has the expected behaviour, it doesn't remove/show the wrong thing from the modeline anymore. Nice!

**Comment by protesilaos** [comment]
Thank you!  I installed the patch.  We can safely close this now.  I will bump the version to 0.1.1 for the package to be rebuilt.

**Comment by linuxer0x42** [comment]
> Thank you! I installed the patch. We can safely close this now. I will bump the version to 0.1.1 for the package to be rebuilt.

No problem, nice!
