### ISSUE TITLE
Queries need to be quoted or escaped before passing them to the shell

### ISSUE THREAD

**Issue by sdelafond** [protesilaos/notmuch-indicator#3]
Trying to use a `:query` containing for instance parenthesis fails with a shell error that ends up showing in the modeline, like `label:zsh: number expected`.

This is easily verified on the command-line:
```
# notmuch count tag:foo and (tag:bar or tag:baz)           
zsh: number expected
```

Quoting it works as expected:
```
# notmuch 'count tag:foo and (tag:bar or tag:baz)'
0
```

Single-quoting the entire query is probably not the best solution here, incase the user query already contains single quotes: `shell-quote-argument` will do a much better job.

**Comment by protesilaos** [comment]
> From: Sébastien Delafond ***@***.***>
> Date: Tue,  7 May 2024 00:15:27 -0700
>

> [... 14 lines elided]

> Single-quoting the entire query is probably not the best solution
> here, incase the user query already contains single quotes:
> `shell-quote-argument` will do a much better job.

Sounds good! Do you want to send the patch or pull request?

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by protesilaos** [comment]
Okay, done! Thanks!
